name: atma_kitchen_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  fluttertoast: ^8.2.2
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.7.0

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  google_nav_bar: ^5.0.6
  image_picker: ^1.0.4
  animated_text_kit: ^4.2.2
  photo_view: ^0.14.0
  http: ^1.1.0
  flutter_riverpod: ^2.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
