name: atma_kitchen_mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  fluttertoast: ^8.2.2
  google_nav_bar: ^5.0.6
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.17.0
  photo_view: ^0.14.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/kitchen.jpg
